### ISSUE TITLE
Vendor.js not included in app compile from 4535 branch

### ISSUE THREAD

**Issue by tomzemp** [pepfar-datim/datim-approvals#10]
When running `gulp build-prod` on https://github.com/pepfar-datim/datim-approvals/tree/4535, app compiles without errors, but `/vendor/vendor.js` was not included in zip file. This script loads angular, so without it, the app does not install properly.

App compiled successfully with vendor.js script on https://github.com/pepfar-datim/datim-approvals/tree/3332 and only relevant changes were to remove angular component on `4535`: https://github.com/pepfar-datim/datim-approvals/commit/b2d263d6c63313a8e91fe7bc125dadd794a458df

@benguaraldi @jakub-bao

**Comment by jakub-bao** [comment]
won't fix. we expect new version to roll out instead.
