### ISSUE TITLE
Enable TravisCI for automatic test runs

### ISSUE THREAD

**Issue by jakub-bao** [pepfar-datim/datim-approvals#104]
In order to make future code updates easy for other developers we can setup TravisCI for this project.
The tests will run automatically with each code update...

**Comment by jakub-bao** [comment]
Got the server from chuck.
Created `.travis.yml` will continue later after other ticket.

Resources: https://docs.cypress.io/guides/guides/continuous-integration.html#Boot-your-server

**Comment by jakub-bao** [comment]
Build plan should have prob the following

```
git clone
npm install
npm install --only=dev
npm start
cypress run
```

**Comment by jakub-bao** [comment]
Finally I made this to run!

Now getting first errors but will fix them too...

![image](https://user-images.githubusercontent.com/47790868/71123525-d7667c00-21b0-11ea-8bd6-130e54a0365f.png)

**Comment by jakub-bao** [comment]
I think first good step might be to enable viewing videos and screenshots. that will help debug these issues...

**Comment by jakub-bao** [comment]
TravisCI doesn't host videos and requires us to provide our own space. I've created a ticket here:
https://github.com/pepfar-datim/Global/issues/5836

**Comment by benguaraldi** [comment]
#104 is now being tracked at https://jira.pepfar.net/browse/DAT-98. Closing.
