### ISSUE TITLE
Mechanisms SUBMIT ERROR but message says SUCCESS

### ISSUE THREAD

**Issue by jakub-bao** [pepfar-datim/datim-approvals#113]
I've just tried to SUBMIT all 1624 mechanisms on `dev`.
The GUI now works fine but when they got sent to server I received this:

![image](https://user-images.githubusercontent.com/47790868/70273233-b137e980-1777-11ea-9d05-072bfb129c2f.png)

But the GUI said `Mechanisms(s) successfully` submitted.

GUI should reflect server response.

**Comment by jakub-bao** [comment]
Will test with this: `http://localhost:3003/#/action?action=view&approvalCombos=XOivy2uDpMF%3AlnSs5OhS8Bs%3AeiLqJfVuWE9%3A&period=2019Q3&workflow=RwNpkAM7Hw7`

![image](https://user-images.githubusercontent.com/47790868/70660451-3a479880-1c30-11ea-846e-0aad191b3b09.png)

**Comment by jakub-bao** [comment]
todo:

1. better color
2. don't autoclose on error!

**Comment by jakub-bao** [comment]
Done.

@benguaraldi This is an error dialog in case there is a server error... Do you have any recommendations on the style/wording?

![image](https://user-images.githubusercontent.com/47790868/70741044-7fc79c80-1ce8-11ea-8990-4051b05badb6.png)

**Comment by benguaraldi** [comment]
Could you make the color #f50057?  Also, I might change the text to `Server error: Failed to submit mechanism(s)`

It'd be better if we could remove the `(s)` and tell if there's one or multiple mechs, especially on the success dialogue.  Is that tricky?

**Comment by benguaraldi** [comment]
By #f50057, I mean whatever color the Submit Mechanisms button is.  :)

**Comment by jakub-bao** [comment]
@benguaraldi 

> Could you make the color #f50057?

I tried that alternative first. But I thought it's a bit confusing because that is a "positive" color rather than "error" color.. that's why I picked the outstanding red.

But I might be wrong... what do you think?

![image](https://user-images.githubusercontent.com/47790868/70743023-dafb8e00-1cec-11ea-9d7f-0f8c0340d7fe.png)

**Comment by jakub-bao** [comment]
@benguaraldi This is with all your comments incorporated:

![image](https://user-images.githubusercontent.com/47790868/70743231-55c4a900-1ced-11ea-9e5d-b96520879266.png)


FYI, the plural was easy... :)

![image](https://user-images.githubusercontent.com/47790868/70743259-64ab5b80-1ced-11ea-9d39-a549fa84e3d2.png)

**Comment by benguaraldi** [comment]
Looks good!

**Comment by jakub-bao** [comment]
ok
