### ISSUE TITLE
Alphabetize ALL MECHANISMS OVERVIEW

### ISSUE THREAD

**Issue by jakub-bao** [pepfar-datim/datim-approvals#127]
![image](https://user-images.githubusercontent.com/47790868/70569937-e8880b00-1b68-11ea-9708-dc5a77122925.png)

**Comment by jakub-bao** [comment]
fixed.
![image](https://user-images.githubusercontent.com/47790868/70648833-ef228b00-1c19-11ea-87af-79bf26544fae.png)

**Comment by benguaraldi** [comment]
Is the trailing comma on Agency because there's a blank Agency?

**Comment by jakub-bao** [comment]
@benguaraldi wow, good catch! let me figure out. but I bet that's the case.

**Comment by jakub-bao** [comment]
It goes back to these guys :)

![image](https://user-images.githubusercontent.com/47790868/70649953-26923700-1c1c-11ea-9cb3-df90886568e8.png)

**Comment by jakub-bao** [comment]
Fixed.

![image](https://user-images.githubusercontent.com/47790868/70650147-8983ce00-1c1c-11ea-902c-d2a6210386d0.png)

(i didn't remove the 00100 but made sure to remove trailing coma in case there is some information missing)
