### ISSUE TITLE
Select ALL mechs: Offer to deselect outstanding

### ISSUE THREAD

**Issue by jakub-bao** [pepfar-datim/datim-approvals#128]
![image](https://user-images.githubusercontent.com/47790868/70570008-0fded800-1b69-11ea-88c3-e9db4fd6fdb3.png)

Feature to offer to deselect outstanding statuses...

**Comment by jakub-bao** [comment]
not MVP

**Comment by jakub-bao** [comment]
Done... this needed a little JS crafting :)

![statuses](https://user-images.githubusercontent.com/47790868/71032800-15e23500-20e4-11ea-8773-622dc9b3a480.gif)

@benguaraldi What do you think about the message/UI? Any recommendations?

**Comment by benguaraldi** [comment]
@jakub-bao Looks fantastic! No changes.

**Comment by jakub-bao** [comment]
ok
