### ISSUE TITLE
Totals sometime not working

### ISSUE THREAD

**Issue by jakub-bao** [pepfar-datim/datim-approvals#129]
![image](https://user-images.githubusercontent.com/47790868/70570158-5df3db80-1b69-11ea-8c4e-9ea389373474.png)

This number was missing sometime...

**Comment by jakub-bao** [comment]
Steps to reproduce:

1. go to `http://localhost:3003/#/action?action=view&approvalCombos=f5RoebaDLMx%3ABOKwiEdAMzQ%3AJPmbX9ZfXmd%3A&approvalCombos=f5RoebaDLMx%3ABaAWvLUBS9a%3Ao9IHCJEfiXL%3A&period=2019Q3&workflow=RwNpkAM7Hw7`
2. switch to to `MER Results: Facility based`
3. switch to different mechanism and check total. If it's present switch again.

**Comment by jakub-bao** [comment]
Another example:

![image](https://user-images.githubusercontent.com/47790868/71100713-7f655080-2183-11ea-9192-f4f8678d3237.png)

Steps to repro:
1. MER results, Global
2. Select all

**Comment by jakub-bao** [comment]
The first example might be yet something else...

**Comment by jakub-bao** [comment]
it's very hard to reproduce... will try again later.

**Comment by benguaraldi** [comment]
Haven't seen this in a while.  Closing.
