### ISSUE TITLE
Limit overview length (ellipsis)

### ISSUE THREAD

**Issue by jakub-bao** [pepfar-datim/datim-approvals#130]
![image](https://user-images.githubusercontent.com/47790868/70570393-ce9af800-1b69-11ea-97c4-d31a82a757fb.png)

**Comment by jakub-bao** [comment]
![tabs](https://user-images.githubusercontent.com/47790868/70650515-3a8a6880-1c1d-11ea-8c25-e8d48ebdea0f.gif)

Is this ok?

We can add more features..
`show less` (to colapse)
and instead of having binary state (closed/open) I can make it unveil the content part by part.

**Comment by benguaraldi** [comment]
I would skip it on the OUs if that's not too hard.  Those aren't that long.  And maybe have the `Show More` on its own line?

**Comment by jakub-bao** [comment]
![image](https://user-images.githubusercontent.com/47790868/70652204-36137f00-1c20-11ea-9513-ac299b035487.png)

**Comment by jakub-bao** [comment]
whoops... this one:

![image](https://user-images.githubusercontent.com/47790868/70652352-7672fd00-1c20-11ea-89e1-3c5e24a7e308.png)

**Comment by benguaraldi** [comment]
Looks great!
