### ISSUE TITLE
Better logout screen

### ISSUE THREAD

**Issue by jakub-bao** [pepfar-datim/datim-approvals#141]
Rarely it can happen that user is in the Approvals app but they got logged out of DHIS2..

We should make sure they see appropriate error message for that...

**Comment by jakub-bao** [comment]
@benguaraldi 

I've put together this.

![image](https://user-images.githubusercontent.com/47790868/70821746-dcd75700-1da9-11ea-9df4-5accc3aa2001.png)

Approve or not approve?

**Comment by benguaraldi** [comment]
Looks good!  Could you capitalize DATIM in the third bullet?  (It should always be caps.)

Also, could you either hyperlink or write in the URL https://datim.zendesk.com/ for `contact DATIM Support`?  Support should be capitalized too.

**Comment by jakub-bao** [comment]
@benguaraldi Got it. Done.

![image](https://user-images.githubusercontent.com/47790868/70827514-680b1980-1db7-11ea-9808-7561c69fa23f.png)

**Comment by benguaraldi** [comment]
@jakub-bao Sorry—I meant just the "S" in DATIM Support.  Thanks!

**Comment by jakub-bao** [comment]
haha, that makes much more sense! I was surprised :)

![image](https://user-images.githubusercontent.com/47790868/70922911-e99bbb00-1ff4-11ea-8adc-a7f2a0e579d6.png)


done.
