### ISSUE TITLE
Upgrade API calls to 2.33

### ISSUE THREAD

**Issue by jakub-bao** [pepfar-datim/datim-approvals#142]
DHIS2 `2.33` moved `/dhis-web-reporting/generateDataSetReport.action` endpoint to `/api/dataSetReport/custom`.

1. We'll have to change URL for the API call at the time of 2.33 upgrade.
2. Aggregated data calls are not working yet. Waiting for: https://jira.dhis2.org/browse/DHIS2-8008

More info in Global repo link: https://github.com/pepfar-datim/Global/issues/5724

**Comment by jakub-bao** [comment]
Hm, the app is not getting even a list of mechanisms right now on `2.33`:

![image](https://user-images.githubusercontent.com/47790868/72382146-a5c8ce00-36e6-11ea-96a0-b43e98f6a459.png)

**Comment by jakub-bao** [comment]
Fixed.

**Comment by benguaraldi** [comment]
Note that, according to Jim, Jira 8008 is not an issue.

**Comment by jakub-bao** [comment]
@benguaraldi Correct.

**Comment by jakub-bao** [comment]
`newrelease` is unfortunately empty dataentry wise.
I have to put in some data to test the aggregations feature:

![image](https://user-images.githubusercontent.com/47790868/72383064-a5313700-36e8-11ea-8148-fd961a1c156f.png)

**Comment by jakub-bao** [comment]
Another screenshot:

![image](https://user-images.githubusercontent.com/47790868/72383336-415b3e00-36e9-11ea-8a64-f0c3a360985f.png)

**Comment by jakub-bao** [comment]
Now, let's confirm the value is stored in Analytics tables using Pivot table and adding the following data element:

`HTS_TST (N, DSD_NARRATIVE): HTS received results`

**Comment by jakub-bao** [comment]
It's in the `analytics` table:
![image](https://user-images.githubusercontent.com/47790868/72462481-2b0fb980-379f-11ea-81a1-5909bc533215.png)

**Comment by jakub-bao** [comment]
Pivot table:
![image](https://user-images.githubusercontent.com/47790868/72462632-7e820780-379f-11ea-94a4-56a3d74ce97e.png)

**Comment by jakub-bao** [comment]
Testing URL for `newrelease` to view the two above mechanisms:

`http://localhost:3003/#/action?approvalCombos=XOivy2uDpMF%3AlnSs5OhS8Bs%3AeiLqJfVuWE9%3A&approvalCombos=XOivy2uDpMF%3AGQXcFddMFIx%3AWCHGpM6T7Va%3A&period=2019Q4&workflow=RwNpkAM7Hw7`

**Comment by jakub-bao** [comment]
Getting this strange error:
![image](https://user-images.githubusercontent.com/47790868/72464435-411f7900-37a3-11ea-9012-6d1837005870.png)
`cannot find acceptable representation`

If I copy the same URL in my browser it works:

![image](https://user-images.githubusercontent.com/47790868/72464489-5d231a80-37a3-11ea-8692-551e37571ed9.png)

Might be something with HTTP headers...

**Comment by jakub-bao** [comment]
If I export the successful request as CURL it works:

`curl 'https://newrelease.datim.org/api/dataSetReport/custom?ds=jKdHXpBfWop&filter=SH885jaRe0o:eiLqJfVuWE9;WCHGpM6T7Va&ou=ybg3MO3hcf4&pe=2019Q4&selectedUnitOnly=false' -H 'authority: newrelease.datim.org' -H 'pragma: no-cache' -H 'cache-control: no-cache' -H 'upgrade-insecure-requests: 1' -H 'user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.117 Safari/537.36' -H 'sec-fetch-user: ?1' -H 'accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9' -H 'sec-fetch-site: none' -H 'sec-fetch-mode: navigate' -H 'accept-encoding: gzip, deflate, br' -H 'accept-language: en-US,en;q=0.9' -H 'cookie: JSESSIONID=3291DDBD9EA8042EBAECCC994E30FB75' --compressed
`

And the failing doesn't work:
`curl 'https://newrelease.datim.org/api/dataSetReport/custom?ds=jKdHXpBfWop&filter=SH885jaRe0o:eiLqJfVuWE9;WCHGpM6T7Va&ou=ybg3MO3hcf4&pe=2019Q4&selectedUnitOnly=false' -H 'authority: newrelease.datim.org' -H 'pragma: no-cache' -H 'cache-control: no-cache' -H 'origin: http://localhost:3003' -H 'user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.117 Safari/537.36' -H 'accept: */*' -H 'sec-fetch-site: cross-site' -H 'sec-fetch-mode: cors' -H 'referer: http://localhost:3003/' -H 'accept-encoding: gzip, deflate, br' -H 'accept-language: en-US,en;q=0.9' -H 'cookie: JSESSIONID=3291DDBD9EA8042EBAECCC994E30FB75' --compressed`

**Comment by jakub-bao** [comment]
Well, this is the diff of the files...
![image](https://user-images.githubusercontent.com/47790868/72465266-dff8a500-37a4-11ea-969b-5ed28f20d24e.png)

**Comment by jakub-bao** [comment]
`-H 'accept: text/html' ` does the trick.

**Comment by jakub-bao** [comment]
I am done here. `Data Approval` app has been fixed to be compatible with DHIS `2.33`.
I've updated deploy scripts in Global repo `releases/dhis-2.33`.

I've also test deployed it to `newrelease`:
https://newrelease.datim.org/api/apps/Data-Approval/index.html#/search

@benguaraldi Should we request testers to take a look at the new version?

**Comment by benguaraldi** [comment]
JB's team is going to test it.  Thanks!

**Comment by jakub-bao** [comment]
FYI, cc @oodujebe

**Comment by benguaraldi** [comment]
This is mostly complete, but due to [Jira 8152](https://jira.dhis2.org/browse/DHIS2-8152)—i.e., that the mechanisms must be submitted via GET instead of POST—the forms do not aggregate when more than 30 or so mechanisms are selected.

I talked to @ssearle-bao and @hardingt and we decided that when there are more than 30 mechanisms selected, the forms should not appear at all, and instead a message should appear in their place:
> Data cannot be shown when more than 30 mechanisms are selected

This can replace this note (in the same font):
> Note: Mechanism preview is limited to 30 mechanisms only

I believe the All Mechanisms Overview section is still possible—is that correct?

That would leave these parts of the screen removed:
![Screen Shot 2020-05-08 at 3 54 56 PM mod](https://user-images.githubusercontent.com/852673/81445506-fc9b5d00-9146-11ea-91c7-0a52675f9691.png)

The note should go under the All Mechanisms Overview, Name, OU, Agency, Partner, and Status.

Thanks!

**Comment by ssearle-bao** [comment]
Hey @benguaraldi , it would be good if it were clear to the approver that just because the data can't be shown, they can still approve. Could we update the messaging to be something like: 

> Data cannot be shown when more than 30 mechanisms are selected. You can still approve these mechanisms.

Or something like that. Thoughts?

**Comment by ssearle-bao** [comment]
I'm also realizing that on this screen they wouldn't be able to see the mechanisms they are approving....that might be a problem.

**Comment by benguaraldi** [comment]
We could change `Name`: `All Mechanisms Overview` to `Mechanisms`: and then a list of mechanism numbers when it's more than 30.  Would that work?

In order to get to the "Data cannot be shown..." message, the user will have to scroll past the button where they can move the mechanisms—do we still need the second sentence?  If so, we'll have to write it differently, as they might be recalling or submitting or whatever.

**Comment by benguaraldi** [comment]
@ssearle-bao Here's what the top looks like:
![Screen Shot 2020-05-08 at 4 03 30 PM](https://user-images.githubusercontent.com/852673/81446952-bc89a980-9149-11ea-876f-bf3fe0d0b5a3.png)

**Comment by benguaraldi** [comment]
@jakub-bao convinced me that we should keep the tabs, as they still give info about the mechs.

**Comment by ssearle-bao** [comment]
@benguaraldi @jakub-bao But aren't we limited in the number of tabs that will display?

**Comment by benguaraldi** [comment]
@ssearle-bao Yes, we are, but we thought that 30 tabs would be better than none.

We're still planning to remove the forms and improve the summary as detailed in [this comment](#issuecomment-626007687).

**Comment by jakub-bao** [comment]
Hi, I am done. I've created `Data Approval v 2.0.6` which is fully compatible with `DHIS 2.33`:
https://github.com/pepfar-datim/datim-approvals/releases/tag/2.0.6

Deployed for testing to `nr.testing` here: https://nr.testing.datim.org/api/apps/Data-Approval/index.html#/search

@benguaraldi @ssearle-bao Can we now ask Matt to proceed with testing?

**Comment by benguaraldi** [comment]
Yes, please! 

Cc: @oodujebe

**Comment by mpinardi-bao** [comment]
I can see data is present when under 30 mechanisms are selected. 
Over 30 a message now appears as discussed here.
![DA-morethan30](https://user-images.githubusercontent.com/32461757/81723481-e2b48f80-9450-11ea-94af-a911cbeffcbb.png)

**Comment by benguaraldi** [comment]
Great!  Thanks, @mpinardi-bao!

@ssearle-bao, I think we can close this and see if other issues come up during full regression testing before deploy.  Does that sound good to you?

cc: @hardingt

**Comment by ssearle-bao** [comment]
This is fine; I still recommend the messaging be updated to let the user know that they can still approve the mechanisms even though data cannot be shown, but this can be closed.

**Comment by benguaraldi** [comment]
Oh! I thought I'd convinced you.

@jakub-bao, please update the error message to @ssearle-bao's language, at https://github.com/pepfar-datim/datim-approvals/issues/142#issuecomment-626005718.

Thanks!

**Comment by ssearle-bao** [comment]
It's not urgent. Whatever you decide.

**Comment by benguaraldi** [comment]
Completed.
