### ISSUE TITLE
Approvals - New Version - NewRelease

### ISSUE THREAD

**Issue by mpinardi-bao** [pepfar-datim/datim-approvals#159]
Issue: When loading this (and maybe others) mechanism for viewing the page crashes to white.
Browser: Chrome,Friefox
URL: [approval](https://newrelease.datim.org/api/apps/Data-Approval/index.html#/action?approvalCombos=mdXu6iCbn2G%3AQCJpv5aDCJU%3AmXjFJEexCHJ%3A&period=2019Q4&workflow=RwNpkAM7Hw7)

**Comment by jakub-bao** [comment]
Good catch. Will fix.

cc @benguaraldi

**Comment by jakub-bao** [comment]
@mpinardi-bao I got it fixed. Can you re-test and close the ticket? Thx.

**Comment by mpinardi-bao** [comment]
Fixed...............for now!
