### ISSUE TITLE
2.33 - New Approvals - Mech ListAsc/Desc

### ISSUE THREAD

**Issue by mpinardi-bao** [pepfar-datim/datim-approvals#160]
Issue: The mechanism list sort functionality seems to have ascending and descending backwards. Also it seems possible to sort three ways but only two are represented by the arrows.
Environment: New Release
sort1:
![image](https://user-images.githubusercontent.com/32461757/72828299-5b959e80-3c4a-11ea-9826-4a43fbcd276f.png)
 sort2:
![image](https://user-images.githubusercontent.com/32461757/72828332-68b28d80-3c4a-11ea-8efc-6cd8dd0c73fc.png)
sort3:
![image](https://user-images.githubusercontent.com/32461757/72828357-72d48c00-3c4a-11ea-8a02-bd03877536da.png)

![image-approvals1](https://user-images.githubusercontent.com/32461757/72828077-f04bcc80-3c49-11ea-9f79-88889dcd056a.png)

**Comment by jakub-bao** [comment]
fixed. will post a link next week.

**Comment by jakub-bao** [comment]
@mpinardi-bao Done. Can you re-test here: https://test.datim.org/api/apps/Data-Approval/index.html#/search

**Comment by mpinardi-bao** [comment]
I did validate it is working properly.
