### ISSUE TITLE
2.33 - New Approvals - View button disappear but items remained selected

### ISSUE THREAD

**Issue by mpinardi-bao** [pepfar-datim/datim-approvals#161]
Issue: When selecting mechanisms its possible to cause the action buttons to disappear by click the list tab again. Only works for view as all other tabs clear the list.
Environment: NewRelease
Steps: 
1. In the view tab
2. Select a mechanism in the list
2. Click on the same tab you are on
4. View button is gone.
![image](https://user-images.githubusercontent.com/32461757/72828446-a1526700-3c4a-11ea-855d-0da5148d729c.png)
![image](https://user-images.githubusercontent.com/32461757/72828480-b29b7380-3c4a-11ea-93c7-e0034df6e407.png)

**Comment by jakub-bao** [comment]
ha! nice catch!

**Comment by jakub-bao** [comment]
fixed. will post a link with deployed app next week.

**Comment by jakub-bao** [comment]
@mpinardi-bao Done. Can you re-test here: https://test.datim.org/api/apps/Data-Approval/index.html#/search

**Comment by mpinardi-bao** [comment]
Validate that the button no longer disappears. Closing ticket.
