### ISSUE TITLE
2.33 - New Approvals - Mechanism Status Action Buttons Enabled after clicking

### ISSUE THREAD

**Issue by mpinardi-bao** [pepfar-datim/datim-approvals#162]
Issue: Mechanism Action status action buttons (accept,submit,etc) are still clickable which the previous click action is still being finished.
Steps: 1) Open a mech you can edit.
2) click an action
3) click the same action again
4) the action will occur twice.

**Comment by jakub-bao** [comment]
@mpinardi-bao Done. Can you re-test here: https://test.datim.org/api/apps/Data-Approval/index.html#/search

**Comment by mpinardi-bao** [comment]
Validate that the buttons are gone for a seconds and reload. Which fixes this issue.
