### ISSUE TITLE
2.33 - New Approvals - Recall and Return functionality

### ISSUE THREAD

**Issue by mpinardi-bao** [pepfar-datim/datim-approvals#163]
Issue: Mechanism Action Recall and Return are vague terms and should have mouse over text. The Functionality also seems to be the same. 
Details:
1) Recall should call an submitted (but not accepted?) mechanism back from the level above.
     - Example: Agency user recalls a mechanism that has been submitted to inter-agency. Its now at accepted by agency.
2) Return should return a approved or submitted at my level to the level below (at approved or pending). This would only be enabled on mechanisms the users has rights to submit/approve and not for partner.
   - Example: Inter-Agency user returns a mechanism that has been submitted to inter-agency. Its now at approved by Agency

Example: User Agency - Can Recall when at its own level. Should be return.
![image](https://user-images.githubusercontent.com/32461757/73097627-a1a26a80-3eb5-11ea-8f5e-36f82683ac1d.png)

Example: User Agency - Can Recall and Return when at its own level and approved. Both return to partner.
![image](https://user-images.githubusercontent.com/32461757/73097754-e0d0bb80-3eb5-11ea-89f2-3550baaf9094.png)

**Comment by benguaraldi** [comment]
@jakub-bao We may just want one of the two buttons.  If I recall correctly, the DHIS2 API does the same thing if a mechanism is recalled or returned.

**Comment by jakub-bao** [comment]
@benguaraldi It seems to be quiet complicated.
DHIS2 recognizes two different actions: `recall` & `return`.
Yes, the both have the exact same effect.
However, not always both of them are available.

There are scenarios where DHIS2 allows you to do `recall` only.
Other scenarios where DHIS2 allows you to do `return` only.
And scenarios where DHIS2 allows you to do both `recall` & `return` with the same effect.

I've tried consolidating the buttons but with no success.
I can try again. Probably by hiding them on the front-end and deciding which method to request.

Let me know if that's something we should do.

**Comment by benguaraldi** [comment]
Interesting.  Is it possible to have just one button and then determine which action to take based on the circumstances?  @jimgrace or @hardingt might be able to help you determine how to tell whether recall or return is needed.

**Comment by jakub-bao** [comment]
done
