### ISSUE TITLE
ER Approval process not working in 2.33

### ISSUE THREAD

**Issue by jakub-bao** [pepfar-datim/datim-approvals#166]
I ran into this issue.
Mechanism `17286` was submitted by `partner / asia region`.
But can't be `accepted` by `agency / hhs/cdc`

test account `Hov5`
test url: `https://newrelease.datim.org/api/apps/Data-Approval/index.html#/action?approvalCombos=ptVxnBssua6%3Am0NndYanyMR%3ApgNzq75NaKD%3A&period=2018Oct&workflow=WUD8TApgOu1`

screenshot:
![image](https://user-images.githubusercontent.com/47790868/73968598-ebdd1000-48e7-11ea-9fb4-1291665fccbe.png)

**Comment by jakub-bao** [comment]
@jimgrace This seems like a bug. Can you please take a look?

***Problem*** `Agency` users can't `accept` mechanisms within `ER` workflow.

***Example***
**User**
username: `Hov5`
link `https://newrelease.datim.org/api/users/I6YQeCd59m8.json?fields=userGroups[name],userCredentials[userRoles[name],username]`
![image](https://user-images.githubusercontent.com/47790868/74048638-987ac880-49a0-11ea-82b1-06e70b11dea8.png)

**Mechanism**
`ou`: `Asia Region`
`name`: `14088 - GH001971 - UNAIDS`
`status`: `submitted by partner for both ER & MER`

**Issue**
MER: user `can` accept: `https://newrelease.datim.org/api/dataApprovals?wf=RwNpkAM7Hw7&pe=2018Oct&aoc=m0NndYanyMR&ou=ptVxnBssua6`
![image](https://user-images.githubusercontent.com/47790868/74050106-6dde3f00-49a3-11ea-8b6b-34828294ddf9.png)


ER: user `cannot` accept: `https://newrelease.datim.org/api/dataApprovals?wf=WUD8TApgOu1&pe=2018Oct&aoc=m0NndYanyMR&ou=ptVxnBssua6`
![image](https://user-images.githubusercontent.com/47790868/74049952-2bb4fd80-49a3-11ea-9be9-e51bda17f12d.png)

**Comment by jakub-bao** [comment]
Hm, @jimgrace discovered there is an issue that SQL view for mechanisms tells that this mech is already at level 2:

![image](https://user-images.githubusercontent.com/47790868/74069151-6c287180-49cb-11ea-9c6a-c5cd5feedca6.png)

However, it seems to be on level 5 viewing through the app. Will have to check what's going on.

https://newrelease.datim.org/dhis-web-maintenance/index.html#/sqlViews/dJEdOW1P6Lv

**Comment by jakub-bao** [comment]
Proof:
New approval app vs SQL view:
![image](https://user-images.githubusercontent.com/47790868/74069714-0e952480-49cd-11ea-803d-1275fffb7f14.png)

**Comment by jakub-bao** [comment]
@jimgrace When you get a chance can you take a look at this?

1. login as `cypress-approvals-partner` to `newrelease` (password via private channel)
2. check these two links: `partner can submit`
(link 2a) `https://newrelease.datim.org/api/apps/Data-Approval/index.html#/action?approvalCombos=ptVxnBssua6%3Am0NndYanyMR%3ApgNzq75NaKD%3A&period=2018Oct&workflow=WUD8TApgOu1` 
(link 2b)`api tells partner they can submit` `https://newrelease.datim.org/api/dataApprovals?wf=WUD8TApgOu1&pe=2018Oct&aoc=m0NndYanyMR&ou=ptVxnBssua6`
3. login as superuser and check this link: (link 3a) `sql view tells superuser the mechanism is already at level 2t`
`https://newrelease.datim.org/dhis-web-maintenance/index.html#/sqlViews/dJEdOW1P6Lv`


link 2a: `partner can submit`
![image](https://user-images.githubusercontent.com/47790868/74070108-14d7d080-49ce-11ea-8ebe-de32af27ce9e.png)

link 2b: `api tells partner they can submit`
![image](https://user-images.githubusercontent.com/47790868/74070129-2e791800-49ce-11ea-8067-784e68156795.png)

link 3a `sql view tells superuser the mechanism is already at level 2t`:
![image](https://user-images.githubusercontent.com/47790868/74070172-59636c00-49ce-11ea-956a-068efac4a74e.png)

**Comment by jakub-bao** [comment]
OK, I'll try to debug the approval process using the SQL views.
I'll create a SQL view for only approvals from 1 combination of ou,period,workflow

**Comment by jakub-bao** [comment]
Hypotheses 1: There might be an issue with mechanisms importer.
It imports database approval record for `level 2/accepted` however it doesn't import database records for: `level 5` & `level 4`.
Let me verify that.

Have to refresh `newrelease` for that to start with a fresh dataset. My tests already did some approvals on the target mechanisms.

**Comment by jimgrace** [comment]
@jakub-bao Good idea to use a limited SQL view -- it should make your life saner!

Last I knew, the mechanism importer didn't have anything to do with approval records -- unless somebody's changed that.

There must be an approval record in the database for each level approved. If the database has been patched by script without adhering to this convention, then things could be messed up. But if you start with no approvals for a mechanism/period/workflow and build your way up, you should be able to see if there are any problems with the app or backend software, as opposed to problems with the database.

**Comment by jakub-bao** [comment]
@jimgrace Got you. Thanks.

Okay, I've reloaded all the data to mint condition.

And I can already see the issue.
Looking at the mech as parter tells me it's ready to be submitted by partner.
Agency HQ user is told it's already approved on higher level and we can't do anything:

![image](https://user-images.githubusercontent.com/47790868/74254620-b2791b80-4cbe-11ea-9f46-90c118a64522.png)

**Comment by jakub-bao** [comment]
OK, my hypothesis seems to be right.
I've created a new table in `newrelease` database: `_temp_approvals`
It's a list of all `data approvals` database records.

I can see that for mechanism `17286`/`asia region`/`fy 2018-2019` there is only one DB record and that is level `2/t`. Levels `5-3` are missing.

![image](https://user-images.githubusercontent.com/47790868/74259964-c0329f00-4cc6-11ea-9e05-9d66cae05d3b.png)

This is the query to check on the mentioned mechanism
```
select * from _temp_approvals
where ou_name='Asia Region'
and startdate='2018-10-01'
and workflow='ER Expenditures FYOct'
and mechanism_name='17286 - 6NU2GGH001346 - Care, Support and Treatment - HIV/TB Project'
;
```
----------------------------------------


Now this perfectly explains the issue.
When accessing the app as `partner` the app doesn't see approval records on levels `4-5` and tells the user they're ready to submit the mechanism.
At the same time when accessing the app as `agency hq` the app sees the approval record `2/t` and tells the user this mechanism was already accepted level above you.

Thus the issue from the screenshot.

**Comment by jimgrace** [comment]
I see the problem too. The following query (if I've done it right) shows all the data approvals grouped by workflow, period start date, and mechanism, where the number of approval records do not match the expected number of levels. For example, if the ER workflow has a minimum (number) approval level of 2, we should expect to see 3 approval records, at levels 2, 4, and 5. If a MER workflow has a minimum (number) approval level of 3, we should expect to see 3 approval records, at levels 3, 4, and 5.
```
select w.workflowid, w.name as workflow, p.startdate, c.name as mechanism,
    min(l.level) as minlevel, max(l.level) as maxlevel, count(*)
from dataapproval d
join dataapprovallevel l on l.dataapprovallevelid = d.dataapprovallevelid
join dataapprovalworkflow w on w.workflowid = d.workflowid
join categoryoptioncombo c on c.categoryoptioncomboid = d.attributeoptioncomboid
join period p on p.periodid = d.periodid
group by w.workflowid, w.name, p.startdate, c.name
having count(*) <> (
	select count(*) from dataapprovalworkflowlevels wl
	join dataapprovallevel al on al.dataapprovallevelid = wl.dataapprovallevelid
	where al.level <= 5 and al.level >= min(l.level)
	and wl.workflowid = w.workflowid
)
order by w.name, p.startdate, c.name;
```
This query doesn't show *exactly* what we need to know -- which is that there are approval records for each level at which there should be -- but it's close. It shows approvals where there are clearly the wrong number of records.

I embedded this as a subquery into a larger query to show where the unexpected counts are in terms of workflow and period: (Note that the count column above is the number of approval records for one workflow/period/mechanism, whereas the count column below is the number of mechanisms in that workflow/period having an unexpected approval record count.)
```
select a.workflow, a.startdate, min(a.minlevel), max(a.maxlevel), count(*) from (
select w.workflowid, w.name as workflow, p.startdate, c.name as mechanism,
    min(l.level) as minlevel, max(l.level) as maxlevel, count(*)
from dataapproval d
join dataapprovallevel l on l.dataapprovallevelid = d.dataapprovallevelid
join dataapprovalworkflow w on w.workflowid = d.workflowid
join categoryoptioncombo c on c.categoryoptioncomboid = d.attributeoptioncomboid
join period p on p.periodid = d.periodid
group by w.workflowid, w.name, p.startdate, c.name
having count(*) <> (
	select count(*) from dataapprovalworkflowlevels wl
	join dataapprovallevel al on al.dataapprovallevelid = wl.dataapprovallevelid
	where al.level <= 5 and al.level >= min(l.level)
	and wl.workflowid = w.workflowid
)
order by w.name, p.startdate, c.name
) a
group by a.workflow, a.startdate;
```
On newrelease, this gives the following results:
```
       workflow        | startdate  | min | max | count
-----------------------+------------+-----+-----+-------
 ER Expenditures FYOct | 2017-10-01 |   2 |   5 |   976
 ER Expenditures FYOct | 2018-10-01 |   2 |   2 |   100
 MER Results           | 2013-10-01 |   1 |   1 |    23
 MER Results           | 2017-04-01 |   3 |   5 |     1
 MER Results           | 2019-01-01 |   3 |   5 |     2
 MER Results           | 2019-04-01 |   3 |   5 |     2
 MER Results           | 2019-07-01 |   3 |   5 |     2
 MER Targets           | 2013-10-01 |   1 |   1 |     2
 MER Targets           | 2018-10-01 |   3 |   5 |     2
 MER Targets           | 2019-10-01 |   4 |   5 |     2
(10 rows)
```
From the original query, most of the ER workflow cases with the wrong number of records had 4 approval records, at levels 2, 3, 4, and 5. But approval level 3 (Inter-Agency at orgunit level 3) should not be present for the ER workflow. Perhaps we patched the database by SQL and just included all the levels below (level number greater than) 2, when we should have omitted level 3.

But some of the original query results showed 5 approval records. The following query shows the details for one of these cases:
```
select w.name as workflow, l.level, o.name as orgunit, u.username, d.created
from dataapproval d
join dataapprovallevel l on l.dataapprovallevelid = d.dataapprovallevelid
join dataapprovalworkflow w on w.workflowid = d.workflowid
join categoryoptioncombo c on c.categoryoptioncomboid = d.attributeoptioncomboid
join organisationunit o on o.organisationunitid = d.organisationunitid
join users u on u.userid = d.creator
join period p on p.periodid = d.periodid
where w.workflowid = 116738932 and p.startdate = '2017-10-01'
    and c.name like '10207 %'
order by l.level;
```
The newrelease results are:
```
       workflow        | level | orgunit |     username      |          created
-----------------------+-------+---------+-------------------+-----------------------
 ER Expenditures FYOct |     2 | Global  | frank.burkybile_1 | 2018-12-20 19:57:57...
 ER Expenditures FYOct |     2 | Zambia  | bao-admin         | 2018-12-21 20:50:57...
 ER Expenditures FYOct |     3 | Zambia  | bao-admin         | 2018-12-21 20:50:57...
 ER Expenditures FYOct |     4 | Zambia  | Rodrigo_Zambia    | 2018-12-20 17:50:11...
 ER Expenditures FYOct |     5 | Zambia  | audrastark        | 2018-12-20 16:32:59...
(5 rows)
```
So in addition to the unexpected level 3 record, this somehow has two level 2 records, one at the Global level, as expected, and one at the Zambia level, not expected. The unexpected level 2 record seems to have been inserted by a patch running under bao-admin. My guess is that the other ER mechanisms with level 2 approvals may also have the incorrect level 3 orgUnit instead of the correct level 1 Global.

If we want to fix this, we should make an SQL patch to modify the incorrect data and add any required levels. Note that for old data where we don't expect there to be any more changes (especially 2013 but maybe later as well), this may not be really important. Data entry is locked anyway, and we won't be moving approvals up and down.

For the approval app, really the only important thing is that if we start with a workflow/period/mechanism with no approvals, it should be able to successfully move approvals up and down to all the levels that we use.

**Comment by jakub-bao** [comment]
@jimgrace Very good analysis. Thank you!

Let me re-run your queries on freshly synced prod data to double check this is purely a data problem.
I want to exclude that there is something wrong with our `2.33` upgrade process.

Syncing `dev` now..

@benguaraldi Can you weigh in on what to do about this?

**Comment by jakub-bao** [comment]
I've re-run the query via DataGrip and see the same result.
However, I am trying to reproduce the bug directly in the app.
Using `dev-mickey` but running in some issue. The instance is so slow it won't let me login..

**Comment by jakub-bao** [comment]
I'm blocked for now from confirming if 2.30 data on prod have the same issue like our 2.33 instance.
Waiting on this ticket: https://github.com/pepfar-datim/Global/issues/6060

**Comment by jakub-bao** [comment]
OK. Finally was able to prove this. It's a Data Issue.

**Comment by jakub-bao** [comment]
@benguaraldi yes you are right. closing.
