### ISSUE TITLE
User feedback for Datim Approvals

### ISSUE THREAD

**Issue by jakub-bao** [pepfar-datim/datim-approvals#171]

**Comment by srobertson001** [comment]
@jakub-bao Thanks for sending me the link on this - this looks like it will be really helpful for period closures!

One thing I did notice is that if I try to select mechanisms that are in different statuses, I get the message saying that I cannot proceed with mechanisms that do not have the same status, and the button is grayed out, but I can still click on the button anyway. It looks like it gets stuck on 'Loading Mechanism State' if I do that.

![image](https://user-images.githubusercontent.com/51675192/75066018-09010980-54b8-11ea-8a1c-77a9f532d507.png)

![image](https://user-images.githubusercontent.com/51675192/75066057-16b68f00-54b8-11ea-95bf-fc56f36776a2.png)
