### ISSUE TITLE
ER Approval process 2.30 - AgencyHQ fail to submit

### ISSUE THREAD

**Issue by mpinardi-bao** [pepfar-datim/datim-approvals#172]
Issue: Failure to submit mechanism at Agency HQ level
Server: test.datim.org
![er-approvals](https://user-images.githubusercontent.com/32461757/75169302-494dcb00-56f6-11ea-82fb-baa0a6cca90e.png)

Steps to reproduce:
1. Create a agencyHQ user
2. Submit a ER mechanism up to AgencyHQ level
3. Using the AgencyHQ user. Open mechanism.
4 Accept the mechanism.
5. Submit the mechanism.
6. An error should occur.

**Comment by jakub-bao** [comment]
Hm, I see the problem.

Direct Link: `https://test.datim.org/api/apps/Data-Approval/index.html#/action?approvalCombos=l1KFEXKI4Dg%3AZXREKkuY7pT%3AEaiJuDWTpGd%3A&period=2019Oct&workflow=WUD8TApgOu1`

@benguaraldi I am lost here. I am 99% sure that this is a data problem. The app just works fine. However, DHIS2 responds with `409 Conflict` response.

@jimgrace Would you help guessing what's happening here? You can try logging in as super-user, opening the URL and submitting the mechanism. Thanks!

**Comment by jimgrace** [comment]
@jakub-bao When using Debugger tools, it looks like the approvals app is trying to submit from Agency HQ level using orgUnit l1KFEXKI4Dg, which is Botswana. But Agency HQ is at the Global level, so the orgUnit for submitting an approval at this level needs to be Global.

**Comment by jakub-bao** [comment]
@jimgrace Thanks so much! Very good find. I'll check and hopefully fix.

**Comment by jakub-bao** [comment]
@jimgrace You were right. I can see that the old app works in this scenario just fine.
And it uses Global as org unit for this call:
![image](https://user-images.githubusercontent.com/47790868/76238707-a70a0900-6206-11ea-90f8-b6d462d41c4b.png)

**Comment by jakub-bao** [comment]
However, the surprising thing is that this same API call with wrong OU (Botswana) is working just fine on dev-jakub but not here.

**Comment by jakub-bao** [comment]
@mpinardi-bao Hi Matt, I was finally able to figure out what's going on and fix it. Thanks to Jim.

Can you please re-test on `test.datim` and confirm it's fixed?

cc @benguaraldi

**Comment by pepfar-datim-features** [comment]
I do not see your new approvals app on that server.

**Comment by mpinardi-bao** [comment]
@jakub-bao I do not see the new approvals installed on that server.

**Comment by jakub-bao** [comment]
@mpinardi-bao Sorry, I've ran `getProd.sh` because of another ticket and didn't realize it will delete the app.
I've redeployed and you can retest here: https://test.datim.org/api/apps/Data-Approval/index.html#/action?approvalCombos=YM6xn5QxNpY%3AftafnQZ4uml%3AxaSmIchIF7K%3A&period=2019Oct&workflow=WUD8TApgOu1

**Comment by mpinardi-bao** [comment]
I validate it is now working as expected.
