### ISSUE TITLE
Submit all mechs taking long time

### ISSUE THREAD

**Issue by jakub-bao** [pepfar-datim/datim-approvals#177]
When submitting all mechanisms it can take a while to get DataSet with aggregation of all data generated. ~3 mins on dev actually :(

I'd like to add a message to the loading dialog which says "Generating Dataset report might take up to several minutes when submitting 1000+ mechanisms at a time"

@benguaraldi Can you help with the phrasing?

**Comment by benguaraldi** [comment]
I recommend writing this under "Loading dataset...":
> (this may take several minutes)

I think it's fine to put that message even when it's fast.

**Comment by jakub-bao** [comment]
done.
