### ISSUE TITLE
When many mechanisms are selected, All Mechanisms Overview seems to hang

### ISSUE THREAD

**Issue by benguaraldi** [pepfar-datim/datim-approvals#193]
When lots of mechanisms are selected, All Mechanisms Overview seems to hang:
![Screen Shot 2020-05-08 at 4 03 30 PM](https://user-images.githubusercontent.com/852673/81445743-7b909580-9147-11ea-84c8-ea653e7c9317.png)

If this isn't easily fixable, maybe we should not try to load the All Mechanisms Overview for large numbers of mechanisms?

**Comment by ssearle-bao** [comment]
We need to be able to load/select all mechanisms for certain functions during period close. I believe this issue has come up before and @jakub-bao was able to fix it. Not sure if related.

**Comment by benguaraldi** [comment]
@ssearle-bao Sorry—I was unclear before.  You can select all mechs, and you can perform functions on them.  Just the page that enables one to do those functions doesn't finish loading, but that doesn't stop one from doing the functions.

**Comment by jakub-bao** [comment]
Note: There is an issue with missing OU in Dedupe adjustments:

{name: "00000 De-duplication adjustment", id: "xEzelmtHWPn", categoryOptionGroups: Array(3), organisationUnits: Array(0), categoryOptionCombos: Array(1)}
mechanism.service.tsx:84 Error: Mechanism has no assigned OU
    at mechanism.service.tsx:84
    at mechanism.service.tsx:99
    at Array.forEach (<anonymous>)
    at mechanism.service.tsx:98
(anonymous) @ main.832624f6.chunk.js:1
(anonymous) @ main.832624f6.chunk.js:1
(anonymous) @ main.832624f6.chunk.js:1
Promise.then (async)
ct @ main.832624f6.chunk.js:1
value @ main.832624f6.chunk.js:1
t @ main.832624f6.chunk.js:1
Pi @ 2.bc53ae92.chunk.js:2
Qa @ 2.bc53ae92.chunk.js:2
Ps @ 2.bc53ae92.chunk.js:2
Ml @ 2.bc53ae92.chunk.js:2
jl @ 2.bc53ae92.chunk.js:2
xl @ 2.bc53ae92.chunk.js:2
vl @ 2.bc53ae92.chunk.js:2
ou @ 2.bc53ae92.chunk.js:2
(anonymous) @ 2.bc53ae92.chunk.js:2
Ol @ 2.bc53ae92.chunk.js:2
cu @ 2.bc53ae92.chunk.js:2
render @ 2.bc53ae92.chunk.js:2
(anonymous) @ main.832624f6.chunk.js:1
Promise.then (async)
1859 @ main.832624f6.chunk.js:1
a @ index.html:1
865 @ main.832624f6.chunk.js:1
a @ index.html:1
i @ index.html:1
e @ index.html:1
(anonymous) @ main.832624f6.chunk.js:1
mechanism.service.tsx:83 {name: "00001 De-duplication adjustment (DSD-TA)", id: "OM58NubPbx1", categoryOptionGroups: Array(3), organisationUnits: Array(0), categoryOptionCombos: Array(1)}
mechanism.service.tsx:84 Error: Mechanism has no assigned OU
    at mechanism.service.tsx:84
    at mechanism.service.tsx:99
    at Array.forEach (<anonymous>)
    at mechanism.service.tsx:98
(anonymous) @ main.832624f6.chunk.js:1
(anonymous) @ main.832624f6.chunk.js:1
(anonymous) @ main.832624f6.chunk.js:1
Promise.then (async)
ct @ main.832624f6.chunk.js:1
value @ main.832624f6.chunk.js:1
t @ main.832624f6.chunk.js:1
Pi @ 2.bc53ae92.chunk.js:2
Qa @ 2.bc53ae92.chunk.js:2
Ps @ 2.bc53ae92.chunk.js:2
Ml @ 2.bc53ae92.chunk.js:2
jl @ 2.bc53ae92.chunk.js:2
xl @ 2.bc53ae92.chunk.js:2
vl @ 2.bc53ae92.chunk.js:2
ou @ 2.bc53ae92.chunk.js:2
(anonymous) @ 2.bc53ae92.chunk.js:2
Ol @ 2.bc53ae92.chunk.js:2
cu @ 2.bc53ae92.chunk.js:2
render @ 2.bc53ae92.chunk.js:2
(anonymous) @ main.832624f6.chunk.js:1
Promise.then (async)
1859 @ main.832624f6.chunk.js:1
a @ index.html:1
865 @ main.832624f6.chunk.js:1
a @ index.html:1
i @ index.html:1
e @ index.html:1
(anonymous) @ main.832624f6.chunk.js:1
mechanism.service.tsx:43 Uncaught (in promise) TypeError: Cannot read property 'id' of undefined
    at mechanism.service.tsx:43
    at Array.filter (<anonymous>)
    at rt (mechanism.service.tsx:43)
    at mechanism.service.tsx:89
    at mechanism.service.tsx:99
    at Array.forEach (<anonymous>)
    at mechanism.service.tsx:98

**Comment by benguaraldi** [comment]
#193 is now being tracked at https://jira.pepfar.net/browse/DAT-99. Closing.
