### ISSUE TITLE
sort mechanisms in overview tabs by alphabet

### ISSUE THREAD

**Issue by jakub-bao** [pepfar-datim/datim-approvals#194]
![image](https://user-images.githubusercontent.com/47790868/96504593-e0860680-1222-11eb-9f31-238f4e5016d6.png)

Steps to reproduce:
- select 10 mechanisms to view. the overview tab will probably be in non-alpha order

**Comment by benguaraldi** [comment]
#194 is now being tracked at https://jira.pepfar.net/browse/DAT-100. Closing.
