### ISSUE TITLE
Check for and display message for no active workflows

### ISSUE THREAD

**Issue by hardingt** [pepfar-datim/datim-approvals#196]
If there are no currently open workflows (per data store settings) data approval app is "stuck" loading workflows, while in the console it logs an error that no workflows are found.

I should say "No currently active workflows, if you feel this is in error, please contact support"

**Comment by jakub-bao** [comment]
done. will deploy

**Comment by benguaraldi** [comment]
@jakub-bao Sorry—I missed the grammar issues in the original message.

Let's change it to:
> There are no workflows active currently.  If you feel this is an error, please contact DATIM Support.

"contact DATIM Support" should link to `https://datim.zendesk.com/`

Thanks!

**Comment by jakub-bao** [comment]
![image](https://user-images.githubusercontent.com/47790868/93794749-80da1280-fc06-11ea-8550-d284a6624026.png)

Does it look good?

**Comment by benguaraldi** [comment]
@jakub-bao Perfect!  Should I test it somewhere?

**Comment by jakub-bao** [comment]
@benguaraldi I just tested it. So I think it's fine.

**Comment by benguaraldi** [comment]
This looks good.  Leaving it open until it's deployed.

**Comment by Nazdar10** [comment]
@benguaraldi @jakub-bao Has this been deployed to test? I was trying to take pre conditions as an IA non super user and it is already showing the message.

**Comment by benguaraldi** [comment]
@Nazdar10 Yes, it looks like at least some version of the most recent approval app was installed on test.

Could you get pre-conditions from triage?  We should probably run patch https://github.com/pepfar-datim/Global/issues/6914 on test, though, to make sure it's the most recent version.

**Comment by benguaraldi** [comment]
Completed.
