### ISSUE TITLE
Superusers see all periods in the datastore

### ISSUE THREAD

**Issue by benguaraldi** [pepfar-datim/datim-approvals#197]
If the user logged in has the role `Superuser ALL authorities`, then they should see all periods in the data store, regardless any restrictions set by the start and end date of the periods.

**Comment by benguaraldi** [comment]
cc: @jason-p-pickering @hardingt

**Comment by jakub-bao** [comment]
ok i think i'm done. will deploy for test.

**Comment by benguaraldi** [comment]
@jakub-bao Looks good!

Could we reverse-sort the periods so that the most recent ones are at the top of the list?

**Comment by benguaraldi** [comment]
@jakub-bao Just looked at this.  Could we reverse-sort by the key rather than the name?  i.e., `2016Q4` rather than `Oct - Dec 2016`?

**Comment by benguaraldi** [comment]
@jakub-bao The most recent version of this looks great!  Thanks!

**Comment by benguaraldi** [comment]
Completed.

**Comment by jason-p-pickering** [comment]
Great work @benguaraldi . This will really help with data change requests!

**Comment by jason-p-pickering** [comment]
Actually, when I open the approvals app in prod, I get this error. Is this only my problem?

`manifest.webapp:1 Manifest: Line: 1, column: 1, Syntax error.`

**Comment by benguaraldi** [comment]
I'm seeing this:
![Screen Shot 2020-10-20 at 3 36 09 AM](https://user-images.githubusercontent.com/852673/96555216-7ce0f500-1285-11eb-9bb9-1f3f0fa6cbd2.png)

Are you opening the DHIS2 approvals app or the DATIM one?

If we are having an issue, we should open a new ticket for it.

**Comment by benguaraldi** [comment]
Oh, and thanks!  The credit goes to @jakub-bao, who did the coding of the feature and kindly alphabetized everything the way I wanted.  :)
