### ISSUE TITLE
Approve multiple mechanisms at once

### ISSUE THREAD

**Issue by jakub-bao** [pepfar-datim/datim-approvals#76]
add checkboxes

**Comment by jakub-bao** [comment]
This became part of other ticket...
![image](https://user-images.githubusercontent.com/47790868/67711462-6799f900-f998-11e9-9ad1-6165987d6a21.png)

**Comment by jakub-bao** [comment]
However, the problem now is on Action page.
since the button label for action comes from URL:
![image](https://user-images.githubusercontent.com/47790868/67711509-86988b00-f998-11e9-9f0c-44c44b4364d6.png)


After doing the action: e.g. Submit. The button still says submit.

**Comment by jakub-bao** [comment]
I think we should downgrade back to mechanism actions...

**Comment by jakub-bao** [comment]
Done. Now time to fix all tests to make sure they accept the new checkboxes!

Then after we'll have to make sure it can also process multiple mechanisms at the same time with the API call.

**Comment by jakub-bao** [comment]
Created a new test for multiple mechanisms...

Now first thing is we need to change the URL:

![image](https://user-images.githubusercontent.com/47790868/67802526-b1024b00-fa61-11e9-9061-b62f61cb1a5e.png)

**Comment by jakub-bao** [comment]
Action page now takes an array of Mechanism IDs in URL.
And fetches info and displays all of them:

![image](https://user-images.githubusercontent.com/47790868/67974328-a4f4c580-fbe8-11e9-9822-13c83705cdd2.png)

Next step will be make sure that also all of them get SUBMITTED/APPROVED.

**Comment by jakub-bao** [comment]
Found out that tests wouldn't work. This change created a few bugs.
Just fixed all of them. Now heading to the multiple mechanism approval.

**Comment by jason-p-pickering** [comment]
Please also test that the client does not create a URL which is too long.
This will result in an NGINX error and could be easy if people have a lot
of mechanisms.

**Comment by jakub-bao** [comment]
Ha, very good point. What do you recommend as a reasonable limit?

**Comment by jason-p-pickering** [comment]
I think this is a question for @alanivey and @chuqyang . Its a limit imposed by Nginx, and but I think anything over 2000 characters will likely cause an error. I would suggest using that as a starting point.

**Comment by chuqyang** [comment]
While we're no longer using nginx on www.datim.org, we still use it on nearly every other system.  The load balancer will support URLs up to 64kb in length. Tomcat will support up to 8177 bytes by default, but that is a configuration directive. 

I'd highly recommend against using a 64kb URL.

**Comment by jason-p-pickering** [comment]
According to this (https://support.microsoft.com/en-us/help/208427/maximum-url-length-is-2-083-characters-in-internet-explorer) 2083 characters is the maximum length for IE. Could we use this as an upper limit (if its true...)

**Comment by jakub-bao** [comment]
Feature done. I have a test to submit multiple mechs at a time.
Just for the sake I'll also add a test to RECALL multiple mechanisms.

@jason-p-pickering Sure I can work with 2083.

**Comment by jakub-bao** [comment]
@jason-p-pickering Actually, not thinking about the issue.
The approvals API has the list of mechanisms in BODY not URL. So this limit shouldn't be a problem.
However, I agree it's not good to leave the app to allow users to approve let's say 1k mechanisms at a time.
No one should need that.

Let me limit it to let's say 20 at a time. Fair enough?

**Comment by jakub-bao** [comment]
Feature is done. Closing this issue and following up with the following tickets:

https://github.com/pepfar-datim/datim-approvals/issues/86
https://github.com/pepfar-datim/datim-approvals/issues/87
https://github.com/pepfar-datim/datim-approvals/issues/88
https://github.com/pepfar-datim/datim-approvals/issues/89
