### ISSUE TITLE
Investigate and solve rapid requests by the approvals app

### ISSUE THREAD

**Issue by jason-p-pickering** [pepfar-datim/datim-approvals#8]
Here is a recent analysis of the DATIM server logs: 

```
# A tibble: 13,913 x 5
   endpoint                                 Referrer                                                        Status      n hit_rate
   <chr>                                    <chr>                                                            <dbl>  <int>    <dbl>
 1 /dhis-web-commons-stream/ping.action     https://www.datim.org/dhis-web-dataentry/index.action              204 476642   0.285 
 2 /api/system/info                         https://www.datim.org/api/apps/Data-Approval/index.html?v=1.5.2    200 192419   0.115 
 3 /api/system/info                         https://www.datim.org/api/apps/Data-Approval/index.html?v=1.5.1    302 150905   0.0903
 4 /api/dataValues                          https://www.datim.org/dhis-web-dataentry/index.action              201 141482   0.0846
 5 /dhis-web-commons/security/login.action  https://www.datim.org/api/apps/Data-Approval/index.html?v=1.5.1    200 115367   0.0690
 6 /api/system/info                         https://www.datim.org/api/apps/Data-Approval/index.html?v=1.5.2    302  86900   0.0520
 7 /dhis-web-commons/security/login.action  https://www.datim.org/api/apps/Data-Approval/index.html?v=1.5.2    200  73036   0.0437
```

This is from a 24 hour period and note that the app is for some reason, making numerous and very rapid requests to two end points: 1) `login.action` and 2) `api/system/info`. Combined, these add up to almost 37% of the hits on the server in one day, which is well **not good.**

This actually places a significant load on the Tomcat server, since both of these requests (unlike the `ping.action) actually get through to the Tomcat server. 

There is no good reason for this to happen, but the actual cause of it is unclear. We need to get to the bottom of this as soon as possible and prevent the app from making rapid and repeated requests to the server. 

If the user is not logged in (due to their session being deactivated) then the app should simply stop working and not continue to do anything. 

Requests to the `api/system/info` are OK, but should not be regarded as absolutely critical, since people are able to get this information from the "About" menu. If we are not able to prevent this from making a request or two, then we should just remove this functionality entirely. 

@benguaraldi please elevate this issue as high as you can with the development team, as it is putting a very high load on the server. 

FYI @Nhobby @mdezalia @Markionium

**Comment by benguaraldi** [comment]
Tracking in https://github.com/pepfar-datim/Global/issues/4535
