### ISSUE TITLE
2.32: Approvals app not loading Approvals

### ISSUE THREAD

**Issue by hardingt** [pepfar-datim/datim-approvals#80]
Jira Ticket: https://jira.dhis2.org/browse/DHIS2-7724

------

2.32 Upgrade

![image](https://user-images.githubusercontent.com/11567315/66751177-63c88b80-ee5c-11e9-9722-849403e16faf.png)

It appears this endpoint is giving a 404 _some of the time_,
https://pilot-rc.datim.org/api/me/dataApprovalLevels?cacheBuster=1571055861669

Investigate and report to Oslo and CC the ticket @jimgrace as he's the Oslo dev in charge of approvals.

**Comment by jimgrace** [comment]
This is a DHIS 2 core issue. I find the Web API call working reliably in 2.31 and previous, and never working in 2.32 onwards. It seems that with 2.32 this code was removed, along with several other /me/... functions that used to be implemented in _CurrentUserController.java_. This module was removed in 2.32.

I will create a Jira ticket for this, and recreate the endpoint in the newer MeController.java for 2.32 and following. Once this is done, it should work as before with no changes needed in DATIM.

**Comment by jimgrace** [comment]
Jira ticket created: https://jira.dhis2.org/browse/DHIS2-7724

**Comment by jimgrace** [comment]
DHIS 2 fix submitted for peer review.

**Comment by hardingt** [comment]
Fantastic @jimgrace thank you!

**Comment by jimgrace** [comment]
This is now fixed in core, and backported to 2.33 and 2.32. The fix should be available in the latest development builds of these versions on dhis2.org within 24 hours (or can be built now from the sources.)
