### ISSUE TITLE
Form preview must show entered data

### ISSUE THREAD

**Issue by jakub-bao** [pepfar-datim/datim-approvals#91]
We don't worry about OU end point parameter when requesting forms via API. Everywhere is Global.
However, we specify dimension.

This is wrong:
![image](https://user-images.githubusercontent.com/47790868/68324358-3a82d000-0095-11ea-9cef-6d466bc60222.png)

**Comment by jakub-bao** [comment]
From discussion with Ben.
When displaying Form previews in the app it must show the data which is being approved.

I bet we have to reference the Mechanism ID in the URL above.

**Comment by jakub-bao** [comment]
Code fixed. Now trying to find a test for this feature on `dev-jakub`...

I'll try to use this mechanism:

![image](https://user-images.githubusercontent.com/47790868/69669468-eea5c400-105f-11ea-9fbe-42d99a0a28df.png)

**Comment by jakub-bao** [comment]
Data Entry

![image](https://user-images.githubusercontent.com/47790868/69669665-4cd2a700-1060-11ea-9ef3-fbfa59a36882.png)

**Comment by jakub-bao** [comment]
![image](https://user-images.githubusercontent.com/47790868/69669755-78ee2800-1060-11ea-94c3-af7c397d8887.png)

**Comment by jakub-bao** [comment]
However, I see no preview of the data in the old approvals app...

![image](https://user-images.githubusercontent.com/47790868/69669923-d2eeed80-1060-11ea-8f99-693b6547953f.png)

![image](https://user-images.githubusercontent.com/47790868/69669969-ea2ddb00-1060-11ea-878a-03277fbba4b3.png)


@benguaraldi Any guess, what am I doing wrong? :-O

**Comment by benguaraldi** [comment]
Yeah, that's bizarre.  I just tried it and it doesn't work for me either.

See:
![Screen Shot 2019-11-26 at 5 07 48 PM](https://user-images.githubusercontent.com/852673/69676709-4c8dd800-106f-11ea-8105-56d8455f4def.png)
![Screen Shot 2019-11-26 at 5 07 40 PM](https://user-images.githubusercontent.com/852673/69676713-4f88c880-106f-11ea-8a70-d784f18f53ea.png)

I also tried it in ben.datim.org.

@hardingt, am I remembering incorrectly?  I thought we could see data values in the approvals app.  Am I remembering wrong or is this broken now?

**Comment by benguaraldi** [comment]
@hardingt is very smart.  The problem is that we need analytics to be run before we see the data values.  @jakub-bao, does that answer your question?

**Comment by jakub-bao** [comment]
@benguaraldi Perfect!

**Comment by jakub-bao** [comment]
![image](https://user-images.githubusercontent.com/47790868/69746232-ceced880-1111-11ea-830b-afea8d52b7f0.png)

Thanks @hardingt and @benguaraldi, now it's working in the old app...

**Comment by jakub-bao** [comment]
The correct form data now appears in form preview.
However, aggregations are missing...

![image](https://user-images.githubusercontent.com/47790868/69747247-0179d080-1114-11ea-9527-b4ccfc28e203.png)

**Comment by benguaraldi** [comment]
@jakub-bao That's great about the data!

Is there a javascript error associated with stella.js? Is the form javascript running?

Also, I assume this works in the angular app, but if it doesn't, that's definitely worth knowing.

**Comment by jakub-bao** [comment]
I was finally able to successfully run analytics on `dev-jakub` yay!
I think the trick was that there was some overnight process which was pending.
Because I tried couple of times on Wednesday and couldn't convince the server to do it.
Now, I can write tests for this feature. Even the aggregations (totals) are working 👍 

I'd just like to create a reproducible way of this for the next time I have to upgrade `dev-jakub` and wipe out the DB.

![image](https://user-images.githubusercontent.com/47790868/69980982-5ac07600-14ff-11ea-9e69-0813d8ee8970.png)

**Comment by benguaraldi** [comment]
Maybe @chuqyang would know the best approach for running analytics on a dev server?

**Comment by jakub-bao** [comment]
Feature done. Test done.

![image](https://user-images.githubusercontent.com/47790868/69981959-5c8b3900-1501-11ea-8cb2-f8ed070d288b.png)

**Comment by jakub-bao** [comment]
@benguaraldi Thanks.
@chuqyang FYI, I've ran `dhis_api_analytics --config-file=/opt/dhis2_jakub/dish.json` and then waited about 1.5hrs but it still wouldn't finish. Even though DHIS2 said `analytics tables created`. The tables were just empty. I gave up and voila on Monday it is populated! 👍 

If there would be a trick to make it faster, let me know please.

**Comment by jakub-bao** [comment]
Hm, reproducing this via SQL after environment refresh seems to be too complicated. There seems to be so many relationships to other tables. I'll just reproduce it manually next time. I've left a comment in the test code:

![image](https://user-images.githubusercontent.com/47790868/69983521-e5f03a80-1504-11ea-8c41-8a85a95c6b41.png)

Closing.
