### ISSUE TITLE
Support submission of all mechanisms (1600+)

### ISSUE THREAD

**Issue by jakub-bao** [pepfar-datim/datim-approvals#94]
Per @benguaraldi ... @hkim224 is ussing the app to submit all.

**Comment by jakub-bao** [comment]
I've found an issue with `117` mechanisms already...

http://localhost:3003/#/action?action=view&approvalCombos=AeVSl0572oK%3AFETQ6OmnsKB&approvalCombos=ttKgFl6uTER%3AFETQ6OmnsKB&approvalCombos=HaTbSiv5ssZ%3AFETQ6OmnsKB&approvalCombos=TIf35UpsbnW%3AFETQ6OmnsKB&approvalCombos=Zbi95z6CKb3%3AFETQ6OmnsKB&approvalCombos=f4FfWEK9qAM%3AFETQ6OmnsKB&approvalCombos=sx1A4BqhcWs%3AFETQ6OmnsKB&approvalCombos=ym9pGBBA3N8%3AFETQ6OmnsKB&approvalCombos=bnSRua1kdBj%3AFETQ6OmnsKB&approvalCombos=TH2WIOxLB3b%3AFETQ6OmnsKB&approvalCombos=SbHa4TSdpKa%3AFETQ6OmnsKB&approvalCombos=CezGh7gd7c3%3AFETQ6OmnsKB&approvalCombos=wtnhREhHiH0%3AFETQ6OmnsKB&approvalCombos=K9tS4oreqpr%3AFETQ6OmnsKB&approvalCombos=YurN2qM9zPZ%3AFETQ6OmnsKB&approvalCombos=RVEcZOT8zwk%3AFETQ6OmnsKB&approvalCombos=yS2aXogKcfS%3AFETQ6OmnsKB&approvalCombos=mNHr3QI3nmb%3AFETQ6OmnsKB&approvalCombos=vnwPtryxDdu%3AFETQ6OmnsKB&approvalCombos=qAjvpO3m82Z%3AFETQ6OmnsKB&approvalCombos=Y14uAWeaYX8%3AFETQ6OmnsKB&approvalCombos=gW1RLajAjL6%3AFETQ6OmnsKB&approvalCombos=RwJwExlyGVs%3AFETQ6OmnsKB&approvalCombos=d8YYeryAm6K%3AFETQ6OmnsKB&approvalCombos=XsgvEXBVmCx%3AFETQ6OmnsKB&approvalCombos=uGfwof10Qxr%3AFETQ6OmnsKB&approvalCombos=PdZ8c2HnLm6%3AFETQ6OmnsKB&approvalCombos=WRi9uAIpfiw%3AFETQ6OmnsKB&approvalCombos=kFfA7I97btM%3AFETQ6OmnsKB&approvalCombos=qd0rsEri7JK%3AFETQ6OmnsKB&approvalCombos=Pph8cQ1uWoi%3AFETQ6OmnsKB&approvalCombos=E0ViVpyOBgD%3AFETQ6OmnsKB&approvalCombos=DharooCpYXR%3AFETQ6OmnsKB&approvalCombos=SRUhTmWndpo%3AFETQ6OmnsKB&approvalCombos=cezL4Ay8YTV%3AFETQ6OmnsKB&approvalCombos=r1obvfBvbgg%3AFETQ6OmnsKB&approvalCombos=uMQO6AIC7FA%3AFETQ6OmnsKB&approvalCombos=oWxVb5P0uPn%3AFETQ6OmnsKB&approvalCombos=tp975AV09cf%3AFETQ6OmnsKB&approvalCombos=IEzsK8RvcrU%3AFETQ6OmnsKB&approvalCombos=xMwNfQczd9L%3AFETQ6OmnsKB&approvalCombos=QI9nL248jTo%3AFETQ6OmnsKB&approvalCombos=WQXDZm4Hcs4%3AFETQ6OmnsKB&approvalCombos=skeHuNEWLJP%3AFETQ6OmnsKB&approvalCombos=G93fIdpOrXp%3AFETQ6OmnsKB&approvalCombos=CaXu7g5BUDt%3AFETQ6OmnsKB&approvalCombos=iASRcWeC3Op%3AFETQ6OmnsKB&approvalCombos=UKFZChfXsDe%3AFETQ6OmnsKB&approvalCombos=KuFkrqI90Lq%3AFETQ6OmnsKB&approvalCombos=pdVbFUbhaXD%3AFETQ6OmnsKB&approvalCombos=JpKD79lBXGz%3AFETQ6OmnsKB&approvalCombos=squJsFONtJn%3AFETQ6OmnsKB&approvalCombos=lQyMwXD7VuW%3AFETQ6OmnsKB&approvalCombos=BHbpOls5Gzr%3AFETQ6OmnsKB&approvalCombos=pzflNUSIQSZ%3AFETQ6OmnsKB&approvalCombos=nyYOwV5K4eL%3AFETQ6OmnsKB&approvalCombos=EEdUP3TDBWi%3AFETQ6OmnsKB&approvalCombos=heOTgi8V2mc%3AFETQ6OmnsKB&approvalCombos=OBbsvVxzIM7%3AFETQ6OmnsKB&approvalCombos=jDG04fEwnSz%3AFETQ6OmnsKB&approvalCombos=xoMmeBiHWmK%3AFETQ6OmnsKB&approvalCombos=tSNkwwtr1Hw%3AFETQ6OmnsKB&approvalCombos=alMZIpFmpxf%3AFETQ6OmnsKB&approvalCombos=U6CehXJlPCh%3AFETQ6OmnsKB&approvalCombos=LaDfLZ00no1%3AFETQ6OmnsKB&approvalCombos=KUsbQbWh4aN%3AFETQ6OmnsKB&approvalCombos=e4jHIyY2MM3%3AFETQ6OmnsKB&approvalCombos=GcDiKFCYPsW%3AFETQ6OmnsKB&approvalCombos=s7m64aBH9pM%3AFETQ6OmnsKB&approvalCombos=eopRiCiby66%3AFETQ6OmnsKB&approvalCombos=KKBElvALs9R%3AFETQ6OmnsKB&approvalCombos=lpexkGYYuGf%3AFETQ6OmnsKB&approvalCombos=RsVQS384d8Z%3AFETQ6OmnsKB&approvalCombos=zkHzHewPjoR%3AFETQ6OmnsKB&approvalCombos=i290eiHkfim%3AFETQ6OmnsKB&approvalCombos=seYSykQ3sl0%3AFETQ6OmnsKB&approvalCombos=HOgJSM6LfQ0%3AFETQ6OmnsKB&approvalCombos=JolMAG9ERiF%3AFETQ6OmnsKB&approvalCombos=dlRP6zGkIWK%3AFETQ6OmnsKB&approvalCombos=EH52CPJE515%3AFETQ6OmnsKB&approvalCombos=MwrpzOKVX2B%3AFETQ6OmnsKB&approvalCombos=yrw3yxej3Dj%3AFETQ6OmnsKB&approvalCombos=uZ2JVdjmIB9%3AFETQ6OmnsKB&approvalCombos=HgqlHuEL3Vx%3AFETQ6OmnsKB&approvalCombos=gf1p5zqKlsR%3AFETQ6OmnsKB&approvalCombos=EEOQQWsUGkW%3AFETQ6OmnsKB&approvalCombos=XcHq6wj4eyh%3AFETQ6OmnsKB&approvalCombos=DOlvswAY9oi%3AFETQ6OmnsKB&approvalCombos=xAJGtlD4qjj%3AFETQ6OmnsKB&approvalCombos=y8ePUg7ybD2%3AFETQ6OmnsKB&approvalCombos=knxHe3Bx3NU%3AFETQ6OmnsKB&approvalCombos=t9llGOcEudv%3AFETQ6OmnsKB&approvalCombos=U9kjfbUsnY4%3AFETQ6OmnsKB&approvalCombos=FZziSXromkj%3AFETQ6OmnsKB&approvalCombos=r9hL6N5TbFC%3AFETQ6OmnsKB&approvalCombos=fnEV1s3M03L%3AFETQ6OmnsKB&approvalCombos=a5DQG6mG8Zp%3AFETQ6OmnsKB&approvalCombos=XwMot8R3Udy%3AFETQ6OmnsKB&approvalCombos=FvJR7Da4DWm%3AFETQ6OmnsKB&approvalCombos=XUFsG9PptJY%3AFETQ6OmnsKB&approvalCombos=LO3OEI78yhw%3AFETQ6OmnsKB&approvalCombos=yA30FzjuBPp%3AFETQ6OmnsKB&approvalCombos=BCtbXsCI0XA%3AFETQ6OmnsKB&approvalCombos=ho2LvjWq7eB%3AFETQ6OmnsKB&approvalCombos=p7y1DsErWfD%3AFETQ6OmnsKB&approvalCombos=lmyw9LdyhwM%3AFETQ6OmnsKB&approvalCombos=MGvzfJSlJfU%3AFETQ6OmnsKB&approvalCombos=lDydEqXvyLh%3AFETQ6OmnsKB&approvalCombos=bf3tygfekMM%3AFETQ6OmnsKB&approvalCombos=WYFoKYAmwOh%3AFETQ6OmnsKB&approvalCombos=PJx1ZrJ5tM0%3AFETQ6OmnsKB&approvalCombos=Wnvrn1Cucwy%3AFETQ6OmnsKB&approvalCombos=Fsy9yOET0Ns%3AFETQ6OmnsKB&approvalCombos=VG9cFsyKeDA%3AFETQ6OmnsKB&approvalCombos=orQi5PI9iO7%3AFETQ6OmnsKB&approvalCombos=vUniSOBaGzb%3AFETQ6OmnsKB&approvalCombos=Txe6yXprqeS%3AFETQ6OmnsKB&period=2018Oct&workflow=WUD8TApgOu1

![image](https://user-images.githubusercontent.com/47790868/69433327-6941ad00-0d09-11ea-8e17-a9159fb1e52c.png)

**Comment by jakub-bao** [comment]
![image](https://user-images.githubusercontent.com/47790868/69434339-68aa1600-0d0b-11ea-91d5-04d2032488e1.png)

**Comment by jakub-bao** [comment]
I'll have to rewrite the Action page to fetch mechanism info in one single query for all mechanisms.

**Comment by jakub-bao** [comment]
This is the mistake:
![image](https://user-images.githubusercontent.com/47790868/69436621-b7f24580-0d0f-11ea-9c18-8a23a08d5c28.png)
Creating a query for each mech.

**Comment by jakub-bao** [comment]
And one more error:
![image](https://user-images.githubusercontent.com/47790868/69436691-db1cf500-0d0f-11ea-9fce-d07ebec74b39.png)

**Comment by jakub-bao** [comment]
Both of these bugs fixed.

**Comment by jakub-bao** [comment]
There's an issue with UI.
If more than 3 mechs are selected they don't fit into the review screen.
I'll prob do these two:

1. Try to fit more mechs in the screen
2. Don't fetch mech info if user selects 10 or more mechs. They won't have time to review them anyway.

Old app doesn't fetch this info at all.

**Comment by jakub-bao** [comment]
Test of submitting 43 mechs at once working fine after above fixes.

![image](https://user-images.githubusercontent.com/47790868/70155750-d3027500-1680-11ea-95db-6da207978440.png)

Will test more.

**Comment by jakub-bao** [comment]
Good old material saved us. They've already implemented scrollable tabs. So the issue with space is fixed.

![image](https://user-images.githubusercontent.com/47790868/70157182-22e23b80-1683-11ea-810f-95855bd924d3.png)


Will limit number of tabs to 30 though not to crash browser.

**Comment by jakub-bao** [comment]
@benguaraldi If user selects more than 30 mechanisms to be accepted they will see this warning...

![image](https://user-images.githubusercontent.com/47790868/70158393-2971b280-1685-11ea-93c0-fa6a35811ecd.png)

What do you think? Do you have a better wording?

**Comment by jakub-bao** [comment]
@benguaraldi I've done the following compromise:

I don't really want to create the "fake tab"... I have an array of objects type `Mechanism` and I don't want to add a dummy object for this purpose. It sounds like a good place for a bug later on.

I came up with another solution:
Count number of clicks on the tabs menu. If user clicks more than 8 times there is a good chance they're at the end of the selection anyways.

Demo:
![tabs](https://user-images.githubusercontent.com/47790868/70168444-e4567c00-1696-11ea-863d-025b44923336.gif)

**Comment by jakub-bao** [comment]
@benguaraldi Live demo here: 
https://dev.datim.org/api/apps/Data-Approval/index.html#/action?action=view&approvalCombos=MXZIoXLc04U%3AnBo9Y4yZubB&approvalCombos=VeTe6LtHycK%3AnBo9Y4yZubB&approvalCombos=OXVIxYEK9Iy%3AnBo9Y4yZubB&approvalCombos=akQsDFtZjIo%3AnBo9Y4yZubB&approvalCombos=WQoacJ8XsVu%3AnBo9Y4yZubB&approvalCombos=hCBvGswtVQc%3AnBo9Y4yZubB&approvalCombos=ADRmvbCwJIs%3AnBo9Y4yZubB&approvalCombos=okiMJY4hvrL%3AnBo9Y4yZubB&approvalCombos=AutP4jJrCfP%3AnBo9Y4yZubB&approvalCombos=LEp02YrgSWt%3AnBo9Y4yZubB&approvalCombos=Vl7Cdnk3Tik%3AnBo9Y4yZubB&approvalCombos=n1Ml9Yg8Fy9%3AnBo9Y4yZubB&approvalCombos=EAyZVtvCeSc%3AnBo9Y4yZubB&approvalCombos=Ybt1c5hEfTT%3AnBo9Y4yZubB&approvalCombos=LwaR3pJRg9V%3AnBo9Y4yZubB&approvalCombos=FUqHo4W3Dj1%3AnBo9Y4yZubB&approvalCombos=mZDi6Owao5Q%3AnBo9Y4yZubB&approvalCombos=AVLyelrC1dd%3AnBo9Y4yZubB&approvalCombos=XULkWCbQdLO%3AnBo9Y4yZubB&approvalCombos=pxkJoUiA9jy%3AnBo9Y4yZubB&approvalCombos=yRZh2CL0Yrx%3AnBo9Y4yZubB&approvalCombos=X3wFHaNjQEx%3AnBo9Y4yZubB&approvalCombos=xGghEN0rM2j%3AnBo9Y4yZubB&approvalCombos=jvMCTZ2Pxp3%3AnBo9Y4yZubB&approvalCombos=tNh5h1Zq5ps%3AnBo9Y4yZubB&approvalCombos=pT6y3oCEISj%3AnBo9Y4yZubB&approvalCombos=tZWI6zzKq9B%3AnBo9Y4yZubB&approvalCombos=at34xkVz0Qm%3AnBo9Y4yZubB&approvalCombos=D5b6zUvnBB4%3AnBo9Y4yZubB&approvalCombos=c1zxbGcDfOQ%3AnBo9Y4yZubB&approvalCombos=kdFsRDJTklT%3AnBo9Y4yZubB&approvalCombos=S0SNQwFQseX%3AnBo9Y4yZubB&approvalCombos=mOTKxiyOvRS%3AnBo9Y4yZubB&approvalCombos=BXucLkQOlnG%3AnBo9Y4yZubB&approvalCombos=T9IYLlu5JQF%3AnBo9Y4yZubB&approvalCombos=wpH2y3ovFQX%3AnBo9Y4yZubB&approvalCombos=l3wLT8DvVqy%3AnBo9Y4yZubB&approvalCombos=gKArRh7nvaI%3AnBo9Y4yZubB&approvalCombos=Ok6ExtdS8lO%3AnBo9Y4yZubB&approvalCombos=MFa8pTuAxnL%3AnBo9Y4yZubB&approvalCombos=p6JPJVjfHI0%3AnBo9Y4yZubB&approvalCombos=FmxMU3zDMNu%3AnBo9Y4yZubB&approvalCombos=nSTbcNoRoUd%3AnBo9Y4yZubB&period=2019Q3&workflow=RwNpkAM7Hw7

:)

**Comment by jakub-bao** [comment]
Submission of all mechanisms still not working :(

![image](https://user-images.githubusercontent.com/47790868/70169665-36000600-1699-11ea-81f2-2ff410834a1c.png)

My guess is that the URL is too long. 
I'll probably move the list of mechanisms from URL to internal state of the application (in memory).
I don't usually like that because that's not compatible with `url sharing` & browser `back`, `forward` buttons... but we don't really have a choice here...

**Comment by jakub-bao** [comment]
Branching off above issue to: https://github.com/pepfar-datim/datim-approvals/issues/107

**Comment by jakub-bao** [comment]
All GUI issues seem to be resolved. I deployed latest version to `dev` and tried to SUBMIT all mechs but ran into this issue:

![image](https://user-images.githubusercontent.com/47790868/70273446-17247100-1778-11ea-95d5-b7e23c46c231.png)

It's weird.. on one side the API seems to tall all mechs are pending at partner.
But the server response says that we can't submit at least one of them.

Have to figure out why...

**Comment by jakub-bao** [comment]
OLD app is just fine doing that.

Comparing the HTTP request of OLD app vs NEW app I can tell there is a difference....

![image](https://user-images.githubusercontent.com/47790868/70274408-1ab8f780-177a-11ea-8683-7b7a705a3863.png)


It seems like we determine a wrong OU for bunch of mechanisms... stemming this into a separate issue...

**Comment by jakub-bao** [comment]
So the mech `QCJpv5aDCJU` is being submitted across all OUs in old app.
In new app it's being submitted for one OU only and multiple times.

That's the issue.

**Comment by jakub-bao** [comment]
It's this repeated mechanism:

![image](https://user-images.githubusercontent.com/47790868/70331511-957f2280-180d-11ea-95df-ba8ef0f8bd35.png)

**Comment by jakub-bao** [comment]
on first glance it looks the same in the old app as well...

![image](https://user-images.githubusercontent.com/47790868/70331613-c8291b00-180d-11ea-954a-6b9e9614e7b3.png)

**Comment by jakub-bao** [comment]
There must be something going under the hood which now decyphers the OUs

![image](https://user-images.githubusercontent.com/47790868/70331874-61f0c800-180e-11ea-949d-ccbd8d10024c.png)

**Comment by jakub-bao** [comment]
so the issue is with this api call

https://dev-jakub.datim.org/api/29/categoryOptions.json?fields=id,name,organisationUnits[id,name],categoryOptionGroups[id,name,groupSets[id]],categoryOptionCombos[id,name]&paging=false&filter=categoryOptionCombos.id:in:[QCJpv5aDCJU,QCJpv5aDCJU,QCJpv5aDCJU,QCJpv5aDCJU,QCJpv5aDCJU]

`https://dev-jakub.datim.org/api/29/categoryOptions.json?fields=id,name,organisationUnits[id,name],categoryOptionGroups[id,name,groupSets[id]],categoryOptionCombos[id,name]&paging=false&filter=categoryOptionCombos.id:in:[QCJpv5aDCJU,QCJpv5aDCJU,QCJpv5aDCJU,QCJpv5aDCJU,QCJpv5aDCJU]`

specially this part:
`filter=categoryOptionCombos.id:in:[QCJpv5aDCJU,QCJpv5aDCJU,QCJpv5aDCJU,QCJpv5aDCJU,QCJpv5aDCJU]`

I noticed that for mechs we have `1 category option` & `1 category option combo`.

However, this assumption must be wrong for the `MOH Alignment` mechanisms.. The api call returns just a single Category Option for multiple Category Option Combos

![image](https://user-images.githubusercontent.com/47790868/70332657-150df100-1810-11ea-84a3-c3b05abf04f0.png)

**Comment by jakub-bao** [comment]
This is the problem

![image](https://user-images.githubusercontent.com/47790868/70340035-03334a80-181e-11ea-9c0a-770311f391e6.png)

**Comment by benguaraldi** [comment]
Is the angular app just excluding the MOH mechs?

**Comment by jakub-bao** [comment]
nope it's showing them..

**Comment by jakub-bao** [comment]
I honestly think the old app is showing WRONG OU for the MOH mechs.
I've tried to mimic the old app and that's why I have it wrong.

**Comment by jakub-bao** [comment]
Phew, submission of ALL mechs finally working!
Even with the MOH adjustments :)
It's working the same way as the old app...

![image](https://user-images.githubusercontent.com/47790868/70342394-e8afa000-1822-11ea-8d95-48fddab70d9b.png)

However, let me try if we can make a test for this feature before closing this.

**Comment by jakub-bao** [comment]
test seems a bit too tricky. closing for now.
